In [2]:
#Array is the line of elements
# one dimension array
# two dimension array
# three dimension array

In [17]:
import numpy as np
a = np.array([8,9,0,]) #one dimension array
a

array([8, 9, 0])

In [16]:
b = np.array([[8,9,0], [0,9,8], [8,0,9]]) #two dimension array
b

array([[8, 9, 0],
       [0, 9, 8],
       [8, 0, 9]])

In [18]:
len(a)

3

In [20]:
a[2]

0

In [22]:
a[0:]

array([8, 9, 0])

In [44]:
import numpy as array
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [45]:
type(a)

numpy.ndarray

In [46]:
#array of zeros
b = np.zeros(4)
b

array([0., 0., 0., 0.])

In [47]:
c = np.empty(3)
c

array([1.3254454e-311, 0.0000000e+000, 4.9406565e-324])

In [48]:
d = np.empty(3)
d

array([1.3254454e-311, 0.0000000e+000, 4.9406565e-324])

In [50]:
#range of an array
e = np.arange(7)
e

array([0, 1, 2, 3, 4, 5, 6])

In [61]:
# with specific range of elements
f = np.arange(21, 32)  #the range will start from 1st integer. last integer is exclusive
f

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [62]:
# continue
g = np.arange(5,60, 5)  #array will start from first integer to middle integer. the last interger is the difference betweeen the integers.
g                       #last digit is exclusive

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [70]:
# linerly spaced arrays
h = np.linspace(3,33, num=11)   #array will start from first integer to last integer. the num= number is the total count of numbers in the output
h

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30., 33.])

In [71]:
#specific data types in array
i = np.ones(4, dtype=np.int8)
i

array([1, 1, 1, 1], dtype=int8)

## 2-D arrays

In [74]:
j = np.zeros([3,4])
j

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [79]:
k = np.ones([5,6])
k

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [77]:
l = np.empty([3,4])
l

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## 3-D array

In [86]:
#making and reshaping
m = np.arange(24).reshape(2,3,4)
m

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

# NumPy practice session

In [3]:
import numpy as np
food = np.array(["samosa", "pakora", "raita"])
food

array(['samosa', 'pakora', 'raita'], dtype='<U6')

In [5]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [6]:
type(price)

numpy.ndarray

In [7]:
type(food)

numpy.ndarray

In [9]:
len(price)

3

In [19]:
#mean
price.mean()

5.0

In [24]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [26]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

# specific interval

In [29]:
#range
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [31]:
np.arange(0,55,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

# Line space

In [35]:
np.linspace(0,10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [36]:
np.linspace(0,25, num=50)

array([ 0.        ,  0.51020408,  1.02040816,  1.53061224,  2.04081633,
        2.55102041,  3.06122449,  3.57142857,  4.08163265,  4.59183673,
        5.10204082,  5.6122449 ,  6.12244898,  6.63265306,  7.14285714,
        7.65306122,  8.16326531,  8.67346939,  9.18367347,  9.69387755,
       10.20408163, 10.71428571, 11.2244898 , 11.73469388, 12.24489796,
       12.75510204, 13.26530612, 13.7755102 , 14.28571429, 14.79591837,
       15.30612245, 15.81632653, 16.32653061, 16.83673469, 17.34693878,
       17.85714286, 18.36734694, 18.87755102, 19.3877551 , 19.89795918,
       20.40816327, 20.91836735, 21.42857143, 21.93877551, 22.44897959,
       22.95918367, 23.46938776, 23.97959184, 24.48979592, 25.        ])

In [39]:
np.linspace(1,1080, num=30)

array([1.00000000e+00, 3.82068966e+01, 7.54137931e+01, 1.12620690e+02,
       1.49827586e+02, 1.87034483e+02, 2.24241379e+02, 2.61448276e+02,
       2.98655172e+02, 3.35862069e+02, 3.73068966e+02, 4.10275862e+02,
       4.47482759e+02, 4.84689655e+02, 5.21896552e+02, 5.59103448e+02,
       5.96310345e+02, 6.33517241e+02, 6.70724138e+02, 7.07931034e+02,
       7.45137931e+02, 7.82344828e+02, 8.19551724e+02, 8.56758621e+02,
       8.93965517e+02, 9.31172414e+02, 9.68379310e+02, 1.00558621e+03,
       1.04279310e+03, 1.08000000e+03])

In [41]:
# Specify data type\
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [42]:
np.ones(13, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

# Array functions

In [2]:
import numpy as np
a = np.array([10,12,15,2,4,6,100,320,0.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [4]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [5]:
b = np.array([10.2,3.4,5.6,91.6,6,10])
b

array([10.2,  3.4,  5.6, 91.6,  6. , 10. ])

In [8]:
c = np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10.2,   3.4,   5.6,  91.6,   6. ,  10. ])

In [10]:
c.sort()
c

array([  0.5,   2. ,   3.4,   4. ,   5.6,   6. ,   6. ,  10. ,  10. ,
        10.2,  10.3,  12. ,  15. ,  91.6, 100. , 320. ])

# 2-D array

In [12]:
d = np.array([[1,2,3,4,5], [5,4,3,2,1]])
d

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [23]:
e = np.array([[6,7], [8,9]])
e

array([[6, 7],
       [8, 9]])

In [25]:
f = np.concatenate((d,e), axis=1)
f

array([[1, 2, 3, 4, 5, 6, 7],
       [5, 4, 3, 2, 1, 8, 9]])